server:
  port : 8080

spring:
  sql:
    init:
      mode: always
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: WARN
    com.warehouse: TRACE